import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Incidencia } from '../models/incidentes.model';

@Injectable({ providedIn: 'root' })
export class IncidenciaService {
  getIncidencias(): Observable<Incidencia[]> {
    const datos: Incidencia[] = [
      {
        id: 'INC003',
        titulo: 'Timeout en generación de reportes',
        descripcion: 'La generación de reportes tarda más de 60 segundos.',
        tipo: 'Rendimiento',
        prioridad: 'Alta',
        estado: 'En progreso',
        modulo_afectado: 'Reportes',
        fecha_creacion: '2025-06-20T08:45:00Z',
        fecha_actualizacion: '2025-06-20T09:10:00Z',
        autor_id: 'USR003',
        responsable_id: 'DEV003',
        archivos_adjunto: ['reporte_error.png'],
        sugerencias: ['Optimizar consultas SQL', 'Implementar paginación'],
        code_smells_relacionados: ['CSM003'],
      },
      {
        id: 'INC004',
        titulo: 'Desfase horario en registros',
        descripcion:
          'Los registros muestran una hora incorrecta por zona horaria.',
        tipo: 'Técnico',
        prioridad: 'Baja',
        estado: 'Abierta',
        modulo_afectado: 'Auditoría',
        fecha_creacion: '2025-06-19T13:20:00Z',
        fecha_actualizacion: '2025-06-19T13:40:00Z',
        autor_id: 'USR004',
        responsable_id: 'DEV002',
        archivos_adjunto: [],
        sugerencias: ['Revisar configuración de TimeZone'],
        code_smells_relacionados: ['CSM002'],
      },
      {
        id: 'INC005',
        titulo: 'Login permite claves vacías',
        descripcion: 'El sistema permite acceder sin ingresar contraseña.',
        tipo: 'Seguridad',
        prioridad: 'Crítica',
        estado: 'Pendiente',
        modulo_afectado: 'Autenticación',
        fecha_creacion: '2025-06-18T07:00:00Z',
        fecha_actualizacion: '2025-06-18T07:30:00Z',
        autor_id: 'USR001',
        responsable_id: 'DEV001',
        archivos_adjunto: ['login_bypass.mp4'],
        sugerencias: ['Agregar validación frontend y backend'],
        code_smells_relacionados: ['CSM005'],
      },
      {
        id: 'INC006',
        titulo: 'Crash al editar perfil',
        descripcion: 'La app se cierra al editar datos personales.',
        tipo: 'Funcional',
        prioridad: 'Alta',
        estado: 'Abierta',
        modulo_afectado: 'Perfil',
        fecha_creacion: '2025-06-17T10:15:00Z',
        fecha_actualizacion: '2025-06-17T10:45:00Z',
        autor_id: 'USR005',
        responsable_id: 'DEV006',
        archivos_adjunto: ['stacktrace.log'],
        sugerencias: ['Revisar tipos de entrada', 'Testear con campos nulos'],
        code_smells_relacionados: ['CSM007'],
      },
      {
        id: 'INC007',
        titulo: 'Notificaciones duplicadas',
        descripcion: 'Se reciben notificaciones dobles por cada evento.',
        tipo: 'Funcional',
        prioridad: 'Media',
        estado: 'Abierta',
        modulo_afectado: 'Notificaciones',
        fecha_creacion: '2025-06-16T11:00:00Z',
        fecha_actualizacion: '2025-06-16T11:20:00Z',
        autor_id: 'USR006',
        responsable_id: 'DEV008',
        archivos_adjunto: [],
        sugerencias: ['Controlar eventos repetidos'],
        code_smells_relacionados: ['CSM009'],
      },
      {
        id: 'INC008',
        titulo: 'Fallo al cargar avatar',
        descripcion: 'Las imágenes de perfil no se muestran correctamente.',
        tipo: 'UI/UX',
        prioridad: 'Baja',
        estado: 'Cerrada',
        modulo_afectado: 'Usuarios',
        fecha_creacion: '2025-06-15T09:00:00Z',
        fecha_actualizacion: '2025-06-15T09:15:00Z',
        autor_id: 'USR007',
        responsable_id: 'DEV010',
        archivos_adjunto: ['avatar_bug.png'],
        sugerencias: ['Validar rutas de imagen'],
        code_smells_relacionados: [],
      },
      {
        id: 'INC009',
        titulo: 'Formulario sin validación de correo',
        descripcion: 'Se aceptan correos sin formato válido.',
        tipo: 'Validación',
        prioridad: 'Media',
        estado: 'En progreso',
        modulo_afectado: 'Contacto',
        fecha_creacion: '2025-06-14T14:30:00Z',
        fecha_actualizacion: '2025-06-14T14:50:00Z',
        autor_id: 'USR008',
        responsable_id: 'DEV004',
        archivos_adjunto: [],
        sugerencias: ['Agregar expresiones regulares'],
        code_smells_relacionados: ['CSM010'],
      },
      {
        id: 'INC010',
        titulo: 'Problemas con carga masiva',
        descripcion: 'Al subir archivos masivos, el sistema se bloquea.',
        tipo: 'Rendimiento',
        prioridad: 'Crítica',
        estado: 'Pendiente',
        modulo_afectado: 'Importaciones',
        fecha_creacion: '2025-06-13T10:00:00Z',
        fecha_actualizacion: '2025-06-13T10:45:00Z',
        autor_id: 'USR009',
        responsable_id: 'DEV005',
        archivos_adjunto: ['import-bug.csv'],
        sugerencias: ['Agregar procesamiento en segundo plano'],
        code_smells_relacionados: ['CSM011'],
      },
      {
        id: 'INC011',
        titulo: 'Botón de eliminar sin confirmación',
        descripcion: 'Se elimina información sin advertencia.',
        tipo: 'UI/UX',
        prioridad: 'Alta',
        estado: 'En progreso',
        modulo_afectado: 'Administración',
        fecha_creacion: '2025-06-12T08:00:00Z',
        fecha_actualizacion: '2025-06-12T08:30:00Z',
        autor_id: 'USR010',
        responsable_id: 'DEV001',
        archivos_adjunto: [],
        sugerencias: ['Agregar diálogo de confirmación'],
        code_smells_relacionados: [],
      },
      {
        id: 'INC012',
        titulo: 'No se muestra historial de cambios',
        descripcion: 'El historial de acciones de usuario no aparece.',
        tipo: 'Funcional',
        prioridad: 'Media',
        estado: 'Abierta',
        modulo_afectado: 'Historial',
        fecha_creacion: '2025-06-11T12:00:00Z',
        fecha_actualizacion: '2025-06-11T12:10:00Z',
        autor_id: 'USR011',
        responsable_id: 'DEV012',
        archivos_adjunto: ['historial.log'],
        sugerencias: ['Revisar integración con base de datos'],
        code_smells_relacionados: ['CSM013'],
      },
    ];
    return of(datos);
  }


  getIncidenciaPorId(id: string): Observable<Incidencia | undefined> {
  const datos: Incidencia[] = [
      {
        id: 'INC003',
        titulo: 'Timeout en generación de reportes',
        descripcion: 'La generación de reportes tarda más de 60 segundos.',
        tipo: 'Rendimiento',
        prioridad: 'Alta',
        estado: 'En progreso',
        modulo_afectado: 'Reportes',
        fecha_creacion: '2025-06-20T08:45:00Z',
        fecha_actualizacion: '2025-06-20T09:10:00Z',
        autor_id: 'USR003',
        responsable_id: 'DEV003',
        archivos_adjunto: ['reporte_error.png'],
        sugerencias: ['Optimizar consultas SQL', 'Implementar paginación'],
        code_smells_relacionados: ['CSM003'],
      },
      {
        id: 'INC004',
        titulo: 'Desfase horario en registros',
        descripcion:
          'Los registros muestran una hora incorrecta por zona horaria.',
        tipo: 'Técnico',
        prioridad: 'Baja',
        estado: 'Abierta',
        modulo_afectado: 'Auditoría',
        fecha_creacion: '2025-06-19T13:20:00Z',
        fecha_actualizacion: '2025-06-19T13:40:00Z',
        autor_id: 'USR004',
        responsable_id: 'DEV002',
        archivos_adjunto: [],
        sugerencias: ['Revisar configuración de TimeZone'],
        code_smells_relacionados: ['CSM002'],
      },
      {
        id: 'INC005',
        titulo: 'Login permite claves vacías',
        descripcion: 'El sistema permite acceder sin ingresar contraseña.',
        tipo: 'Seguridad',
        prioridad: 'Crítica',
        estado: 'Pendiente',
        modulo_afectado: 'Autenticación',
        fecha_creacion: '2025-06-18T07:00:00Z',
        fecha_actualizacion: '2025-06-18T07:30:00Z',
        autor_id: 'USR001',
        responsable_id: 'DEV001',
        archivos_adjunto: ['login_bypass.mp4'],
        sugerencias: ['Agregar validación frontend y backend'],
        code_smells_relacionados: ['CSM005'],
      },
      {
        id: 'INC006',
        titulo: 'Crash al editar perfil',
        descripcion: 'La app se cierra al editar datos personales.',
        tipo: 'Funcional',
        prioridad: 'Alta',
        estado: 'Abierta',
        modulo_afectado: 'Perfil',
        fecha_creacion: '2025-06-17T10:15:00Z',
        fecha_actualizacion: '2025-06-17T10:45:00Z',
        autor_id: 'USR005',
        responsable_id: 'DEV006',
        archivos_adjunto: ['stacktrace.log'],
        sugerencias: ['Revisar tipos de entrada', 'Testear con campos nulos'],
        code_smells_relacionados: ['CSM007'],
      },
      {
        id: 'INC007',
        titulo: 'Notificaciones duplicadas',
        descripcion: 'Se reciben notificaciones dobles por cada evento.',
        tipo: 'Funcional',
        prioridad: 'Media',
        estado: 'Abierta',
        modulo_afectado: 'Notificaciones',
        fecha_creacion: '2025-06-16T11:00:00Z',
        fecha_actualizacion: '2025-06-16T11:20:00Z',
        autor_id: 'USR006',
        responsable_id: 'DEV008',
        archivos_adjunto: [],
        sugerencias: ['Controlar eventos repetidos'],
        code_smells_relacionados: ['CSM009'],
      },
      {
        id: 'INC008',
        titulo: 'Fallo al cargar avatar',
        descripcion: 'Las imágenes de perfil no se muestran correctamente.',
        tipo: 'UI/UX',
        prioridad: 'Baja',
        estado: 'Cerrada',
        modulo_afectado: 'Usuarios',
        fecha_creacion: '2025-06-15T09:00:00Z',
        fecha_actualizacion: '2025-06-15T09:15:00Z',
        autor_id: 'USR007',
        responsable_id: 'DEV010',
        archivos_adjunto: ['avatar_bug.png'],
        sugerencias: ['Validar rutas de imagen'],
        code_smells_relacionados: [],
      },
      {
        id: 'INC009',
        titulo: 'Formulario sin validación de correo',
        descripcion: 'Se aceptan correos sin formato válido.',
        tipo: 'Validación',
        prioridad: 'Media',
        estado: 'En progreso',
        modulo_afectado: 'Contacto',
        fecha_creacion: '2025-06-14T14:30:00Z',
        fecha_actualizacion: '2025-06-14T14:50:00Z',
        autor_id: 'USR008',
        responsable_id: 'DEV004',
        archivos_adjunto: [],
        sugerencias: ['Agregar expresiones regulares'],
        code_smells_relacionados: ['CSM010'],
      },
      {
        id: 'INC010',
        titulo: 'Problemas con carga masiva',
        descripcion: 'Al subir archivos masivos, el sistema se bloquea.',
        tipo: 'Rendimiento',
        prioridad: 'Crítica',
        estado: 'Pendiente',
        modulo_afectado: 'Importaciones',
        fecha_creacion: '2025-06-13T10:00:00Z',
        fecha_actualizacion: '2025-06-13T10:45:00Z',
        autor_id: 'USR009',
        responsable_id: 'DEV005',
        archivos_adjunto: ['import-bug.csv'],
        sugerencias: ['Agregar procesamiento en segundo plano'],
        code_smells_relacionados: ['CSM011'],
      },
      {
        id: 'INC011',
        titulo: 'Botón de eliminar sin confirmación',
        descripcion: 'Se elimina información sin advertencia.',
        tipo: 'UI/UX',
        prioridad: 'Alta',
        estado: 'En progreso',
        modulo_afectado: 'Administración',
        fecha_creacion: '2025-06-12T08:00:00Z',
        fecha_actualizacion: '2025-06-12T08:30:00Z',
        autor_id: 'USR010',
        responsable_id: 'DEV001',
        archivos_adjunto: [],
        sugerencias: ['Agregar diálogo de confirmación'],
        code_smells_relacionados: [],
      },
      {
        id: 'INC012',
        titulo: 'No se muestra historial de cambios',
        descripcion: 'El historial de acciones de usuario no aparece.',
        tipo: 'Funcional',
        prioridad: 'Media',
        estado: 'Abierta',
        modulo_afectado: 'Historial',
        fecha_creacion: '2025-06-11T12:00:00Z',
        fecha_actualizacion: '2025-06-11T12:10:00Z',
        autor_id: 'USR011',
        responsable_id: 'DEV012',
        archivos_adjunto: ['historial.log'],
        sugerencias: ['Revisar integración con base de datos'],
        code_smells_relacionados: ['CSM013'],
      },
    ];
  const resultado = datos.find(i => i.id === id);
  return of(resultado);
}
}
